CREATE TABLE IF NOT EXISTS signature_requests (
  id INT NOT NULL AUTO_INCREMENT,
  company_id INT NOT NULL,
  customer_id INT NULL,
  deal_id INT NULL,
  email_id INT NULL,
  email_attachment_id INT NULL,
  created_by_user_id INT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  file_url TEXT NOT NULL,
  signer_name VARCHAR(255) NOT NULL,
  signer_email VARCHAR(255) NOT NULL,
  status ENUM('draft','sent','viewed','signed','declined','expired') NOT NULL DEFAULT 'draft',
  provider VARCHAR(32) NOT NULL DEFAULT 'signwell',
  provider_document_id VARCHAR(255) NULL,
  fields_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_signature_requests_customer (company_id, customer_id, created_at),
  INDEX idx_signature_requests_email (email_id),
  INDEX idx_signature_requests_attachment (email_attachment_id),
  INDEX idx_signature_requests_provider (provider, provider_document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
