//! Reads and writes the React Router `createCookieSessionStorage` cookie.
//!
//! Wire format (react-router `lib/server-runtime/cookies.ts` + `crypto.ts`):
//!
//! ```text
//! __session = percent_encode( base64(utf8(json)) + "." + base64_nopad(hmac_sha256(secret, base64(utf8(json)))) )
//! ```
//!
//! Keeping this byte-compatible lets the Lambda accept sessions Remix issued,
//! and later issue sessions itself without logging anyone out.

use base64::Engine;
use base64::engine::general_purpose::{STANDARD, STANDARD_NO_PAD};
use hmac::{Hmac, KeyInit, Mac};
use percent_encoding::{AsciiSet, NON_ALPHANUMERIC, percent_decode_str, utf8_percent_encode};
use serde::{Deserialize, Serialize};
use sha2::Sha256;

pub const SESSION_COOKIE_NAME: &str = "__session";

type HmacSha256 = Hmac<Sha256>;

/// The fields of the Remix `SessionData` the API needs. Other keys (QBO tokens,
/// flash messages) are ignored on read.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionData {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Super admins switch companies by storing the target here.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_company_id: Option<i32>,
}

/// Value of the named cookie in a `Cookie` header, percent-decoded the way the
/// `cookie` npm package does it (first occurrence wins, quotes stripped).
pub fn cookie_value(header: &str, name: &str) -> Option<String> {
    header.split(';').find_map(|pair| {
        let (key, value) = pair.split_once('=')?;
        if key.trim() != name {
            return None;
        }
        let value = value.trim();
        let value = value
            .strip_prefix('"')
            .and_then(|v| v.strip_suffix('"'))
            .unwrap_or(value);
        Some(percent_decode_str(value).decode_utf8().ok()?.into_owned())
    })
}

/// Verifies the signature and decodes the session payload. `None` for any
/// tampered, truncated, or foreign cookie.
pub fn decode_session(value: &str, secret: &str) -> Option<SessionData> {
    let (payload, signature) = value.rsplit_once('.')?;
    let signature = STANDARD_NO_PAD
        .decode(signature.trim_end_matches('='))
        .ok()?;
    let mut mac = HmacSha256::new_from_slice(secret.as_bytes()).ok()?;
    mac.update(payload.as_bytes());
    mac.verify_slice(&signature).ok()?;
    let json = STANDARD.decode(payload).ok()?;
    serde_json::from_slice(&json).ok()
}

/// Inverse of [`decode_session`]; returns the percent-encoded cookie value.
pub fn encode_session(data: &SessionData, secret: &str) -> String {
    let json = serde_json::to_vec(data).expect("session data serializes");
    let payload = STANDARD.encode(json);
    let mut mac =
        HmacSha256::new_from_slice(secret.as_bytes()).expect("HMAC accepts any key length");
    mac.update(payload.as_bytes());
    let signature = STANDARD_NO_PAD.encode(mac.finalize().into_bytes());
    utf8_percent_encode(&format!("{payload}.{signature}"), COOKIE_VALUE_ENCODE).to_string()
}

/// `encodeURIComponent` leaves these unescaped.
const COOKIE_VALUE_ENCODE: &AsciiSet = &NON_ALPHANUMERIC
    .remove(b'-')
    .remove(b'_')
    .remove(b'.')
    .remove(b'!')
    .remove(b'~')
    .remove(b'*')
    .remove(b'\'')
    .remove(b'(')
    .remove(b')');

#[cfg(test)]
mod tests {
    use super::*;

    // Generated by react-router 7 `createCookieSessionStorage` with
    // secrets: ['test-secret'] (see api/README.md "Auth").
    const WITH_FLASH: &str = "__session=eyJzZXNzaW9uSWQiOiIxMTExMTExMS0yMjIyLTQzMzMtODQ0NC01NTU1NTU1NTU1NTUiLCJhY3RpdmVDb21wYW55SWQiOjEwMSwiX19mbGFzaF9tZXNzYWdlX18iOnsidGl0bGUiOiLQn9GA0LjQstC10YIg4pyTIiwidmFyaWFudCI6InN1Y2Nlc3MifX0%3D.lS%2B1F9jpvMgIZtkAUO5F7ioiULaxhq4xxP0HP59ekjA";
    const PLAIN: &str = "eyJzZXNzaW9uSWQiOiJhYWFhYWFhYS1iYmJiLTRjY2MtOGRkZC1lZWVlZWVlZWVlZWUifQ%3D%3D.MvwdWs%2B1qdYUAOeCazF9MUALVn3bGB4xsJ6ijvPVX6A";

    #[test]
    fn decodes_react_router_cookie_with_unicode_flash() {
        let header = format!("theme=dark; {WITH_FLASH}; other=1");
        let value = cookie_value(&header, SESSION_COOKIE_NAME).unwrap();
        let data = decode_session(&value, "test-secret").unwrap();
        assert_eq!(
            data.session_id.as_deref(),
            Some("11111111-2222-4333-8444-555555555555")
        );
        assert_eq!(data.active_company_id, Some(101));
    }

    #[test]
    fn encode_matches_react_router_byte_for_byte() {
        let data = SessionData {
            session_id: Some("aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee".into()),
            active_company_id: None,
        };
        assert_eq!(encode_session(&data, "test-secret"), PLAIN);
    }

    #[test]
    fn rejects_wrong_secret_and_tampering() {
        let value = cookie_value(&format!("__session={PLAIN}"), SESSION_COOKIE_NAME).unwrap();
        assert!(decode_session(&value, "other-secret").is_none());
        let tampered = value.replacen("eyJ", "eyK", 1);
        assert!(decode_session(&tampered, "test-secret").is_none());
        assert!(decode_session("no-dot", "test-secret").is_none());
    }

    #[test]
    fn missing_cookie_is_none() {
        assert!(cookie_value("a=1; b=2", SESSION_COOKIE_NAME).is_none());
    }
}
